//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accidente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accidente()
        {
            this.DocumentoAccidente = new HashSet<DocumentoAccidente>();
            this.TestigoAccidente = new HashSet<TestigoAccidente>();
        }
    
        public int IdAccidente { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public string NumeroDeclaracion { get; set; }
        public Nullable<System.DateTime> FechaDeclaracion { get; set; }
        public Nullable<System.DateTime> FechaAccidente { get; set; }
        public string HoraAccidente { get; set; }
        public string HorasTrabajadas { get; set; }
        public string DescripcionAccidente { get; set; }
        public string LugarCiudad { get; set; }
        public string LugarBarrio { get; set; }
        public string LugarCalle { get; set; }
        public string Lugarcomunidad { get; set; }
        public string Lugarotros { get; set; }
        public string Responsabilidad { get; set; }
        public string SitioPreciso { get; set; }
        public string TipoAccidente { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoAccidente> DocumentoAccidente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestigoAccidente> TestigoAccidente { get; set; }
    }
}
