//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AperturaCaja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AperturaCaja()
        {
            this.CierreCaja = new HashSet<CierreCaja>();
        }
    
        public int IdAperturaCaja { get; set; }
        public Nullable<System.DateTime> FechaApertura { get; set; }
        public Nullable<int> IdEncargadoApertura { get; set; }
        public Nullable<decimal> MontoCordoba { get; set; }
        public Nullable<decimal> MontoDolar { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public string Consecutivo { get; set; }
        public Nullable<int> IdAperturaDia { get; set; }
        public Nullable<int> IdCaja { get; set; }
    
        public virtual AperturaDia AperturaDia { get; set; }
        public virtual Caja Caja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CierreCaja> CierreCaja { get; set; }
    }
}
