//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AplicacionBusqueda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AplicacionBusqueda()
        {
            this.CodigoAplicacion = new HashSet<CodigoAplicacion>();
        }
    
        public int IdAplicacion { get; set; }
        public Nullable<int> IdVersion { get; set; }
        public Nullable<int> IdMotor { get; set; }
        public string Transmision { get; set; }
        public string Carroceria { get; set; }
        public string Traccion { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> Anio { get; set; }
    
        public virtual MotorAplicacion MotorAplicacion { get; set; }
        public virtual VersionAplicacion VersionAplicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CodigoAplicacion> CodigoAplicacion { get; set; }
    }
}
