//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AprobarCotizacionMantenimiento
    {
        public int IdAprobarCotizacion { get; set; }
        public Nullable<int> IdCotizacionMantenimiento { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public string Observacion { get; set; }
    
        public virtual CotizarMantenimiento CotizarMantenimiento { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
