//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArqueoCaja
    {
        public int IdArqueoCaja { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Observacion { get; set; }
        public Nullable<decimal> SistemaCordoba { get; set; }
        public Nullable<decimal> SistemaDolar { get; set; }
        public Nullable<decimal> FisicoCordoba { get; set; }
        public Nullable<decimal> FisicoDolar { get; set; }
        public Nullable<decimal> DiferenciaCordoba { get; set; }
        public Nullable<decimal> DiferenciaDolar { get; set; }
        public string Efectivo { get; set; }
        public string Tarjeta { get; set; }
        public string Cheque { get; set; }
        public Nullable<int> IdCierreCaja { get; set; }
    
        public virtual CierreCaja CierreCaja { get; set; }
    }
}
