//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignarMontoCajaChica
    {
        public int IdAsignarMontoCajaChica { get; set; }
        public Nullable<int> IdAsignacionCajaChica { get; set; }
        public Nullable<System.DateTime> FechaAsignacion { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string TipoMoneda { get; set; }
        public string Concepto { get; set; }
        public string TipoTransaccion { get; set; }
        public string Estado { get; set; }
        public string NumeroDocumento { get; set; }
        public string Banco { get; set; }
        public string NumeroCuenta { get; set; }
        public Nullable<int> IdSolicitudReembolsoCajaChica { get; set; }
    
        public virtual AsignacionCajaChica AsignacionCajaChica { get; set; }
    }
}
