//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignarTecnicosOrdenProduccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AsignarTecnicosOrdenProduccion()
        {
            this.DetalleAsignarTecnicosOrdenProduccion = new HashSet<DetalleAsignarTecnicosOrdenProduccion>();
            this.SolicitarProductosOP = new HashSet<SolicitarProductosOP>();
        }
    
        public int IdAsignarTecnicosOrdenProduccion { get; set; }
        public Nullable<int> IdOrdenProduccion { get; set; }
        public Nullable<int> IdEstacion { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual EstacionesProduccion EstacionesProduccion { get; set; }
        public virtual OrdenProduccion OrdenProduccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleAsignarTecnicosOrdenProduccion> DetalleAsignarTecnicosOrdenProduccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitarProductosOP> SolicitarProductosOP { get; set; }
    }
}
