//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignarConductoresVehiculos
    {
        public int IdAsignarConductoresVehiculos { get; set; }
        public Nullable<int> IdConductor { get; set; }
        public Nullable<int> IdFlotaSucursal { get; set; }
        public Nullable<System.DateTime> FechaAsignacion { get; set; }
        public Nullable<System.DateTime> FechaDesasignar { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual Conductores Conductores { get; set; }
        public virtual FlotaSucursal FlotaSucursal { get; set; }
    }
}
