//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BajaPersonal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BajaPersonal()
        {
            this.EvaluacionBaja = new HashSet<EvaluacionBaja>();
        }
    
        public int IdBajaPersonal { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdDesvinculacion { get; set; }
        public Nullable<bool> Recontratable { get; set; }
        public string CausaPrimaria { get; set; }
        public string OtrasCausas { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> FechaEmitido { get; set; }
        public string TipoBaja { get; set; }
    
        public virtual DesvinculacionPersonal DesvinculacionPersonal { get; set; }
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionBaja> EvaluacionBaja { get; set; }
    }
}
