//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bancos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bancos()
        {
            this.ConfiguracionFIN = new HashSet<ConfiguracionFIN>();
            this.CuentaBanco = new HashSet<CuentaBanco>();
            this.CuentaBancaria = new HashSet<CuentaBancaria>();
            this.DetallePagoProveedor = new HashSet<DetallePagoProveedor>();
        }
    
        public int IdBanco { get; set; }
        public string Banco { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> IdCatalagoCuenta { get; set; }
        public Nullable<decimal> CpagoPorTarjeta { get; set; }
    
        public virtual CatalogoCuenta CatalogoCuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfiguracionFIN> ConfiguracionFIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaBanco> CuentaBanco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaBancaria> CuentaBancaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePagoProveedor> DetallePagoProveedor { get; set; }
    }
}
