//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraCobranza
    {
        public int IdBitacora { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdEmpleadoRegistrador { get; set; }
        public string Accion { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string HoraRegistro { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
