//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogoCuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatalogoCuenta()
        {
            this.Bancos = new HashSet<Bancos>();
            this.PagoRealizadoTesoreria = new HashSet<PagoRealizadoTesoreria>();
        }
    
        public int IdCatalogoCuenta { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string NoCuenta { get; set; }
        public string NombreCuenta { get; set; }
        public string CuentaAsociada { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> Nivel { get; set; }
        public string Grupo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bancos> Bancos { get; set; }
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoRealizadoTesoreria> PagoRealizadoTesoreria { get; set; }
    }
}
