//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Celular
    {
        public int IdCelular { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public string Pantalla { get; set; }
        public string Procesador { get; set; }
        public string Ram { get; set; }
        public string Almacenamiento { get; set; }
        public string CamaraTrasera { get; set; }
        public string CamaraFrontal { get; set; }
        public string Bateria { get; set; }
        public string SistemaOperativo { get; set; }
        public string Conectividad { get; set; }
        public string DimensionesPeso { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
