//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteSeguimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClienteSeguimiento()
        {
            this.Consignacion = new HashSet<Consignacion>();
            this.SeguimientoContacto = new HashSet<SeguimientoContacto>();
            this.SolicitudPaseCredito = new HashSet<SolicitudPaseCredito>();
            this.UbicacionCliente = new HashSet<UbicacionCliente>();
            this.SolicitudCredito = new HashSet<SolicitudCredito>();
        }
    
        public int IdClienteSeguimiento { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public string CondicionPago { get; set; }
        public Nullable<int> Plazo { get; set; }
        public string Pais { get; set; }
        public string Ciudad { get; set; }
        public string Direccion { get; set; }
        public string Web { get; set; }
        public string RedSocial { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Codigo { get; set; }
        public string Nacionalidad { get; set; }
        public string Giro { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Ubicacion { get; set; }
        public string RazonSocial { get; set; }
        public Nullable<decimal> MontoCredito { get; set; }
        public Nullable<int> IdSegmento { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consignacion> Consignacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeguimientoContacto> SeguimientoContacto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudPaseCredito> SolicitudPaseCredito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UbicacionCliente> UbicacionCliente { get; set; }
        public virtual Segmento Segmento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudCredito> SolicitudCredito { get; set; }
    }
}
