//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteBanco
    {
        public int IdClienteBanco { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdDatosBancariosCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual DatosBancariosCliente DatosBancariosCliente { get; set; }
    }
}
