//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Combustible
    {
        public int IdCombustible { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string NoCupon { get; set; }
        public Nullable<int> IdConductor { get; set; }
        public Nullable<int> IdVehiculo { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public Nullable<int> Kilometraje { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> IdTipoCombustible { get; set; }
        public Nullable<int> IdEstacion { get; set; }
        public Nullable<int> IdDepartamentoIngresa { get; set; }
        public Nullable<int> IdUsuarioIngresa { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual Conductores Conductores { get; set; }
        public virtual EstacionesCombustibles EstacionesCombustibles { get; set; }
        public virtual FlotaVehicular FlotaVehicular { get; set; }
        public virtual TipoCombustible TipoCombustible { get; set; }
    }
}
