//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra()
        {
            this.AnulacionCompra = new HashSet<AnulacionCompra>();
            this.DetalleCompraEliminados = new HashSet<DetalleCompraEliminados>();
            this.DetalleCompra = new HashSet<DetalleCompra>();
            this.DetallesImpuestos = new HashSet<DetallesImpuestos>();
            this.DevolucionCompra = new HashSet<DevolucionCompra>();
        }
    
        public int IdCompra { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public string Consecutivo { get; set; }
        public string Factura { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string TipoPago { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdBodega { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> RealizadaPor { get; set; }
        public Nullable<int> IngresadoPor { get; set; }
        public string Moneda { get; set; }
        public string SerieConsecutivo { get; set; }
        public string Estado { get; set; }
        public Nullable<int> Plazo { get; set; }
        public string Regimen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnulacionCompra> AnulacionCompra { get; set; }
        public virtual Bodega Bodega { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Empleado Empleado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCompraEliminados> DetalleCompraEliminados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCompra> DetalleCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesImpuestos> DetallesImpuestos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DevolucionCompra> DevolucionCompra { get; set; }
    }
}
