//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfirmarCita
    {
        public int IdConfirmarCita { get; set; }
        public Nullable<int> IdTrabajoCliente { get; set; }
        public Nullable<int> IdAsesor { get; set; }
        public Nullable<System.DateTime> FechaCita { get; set; }
        public Nullable<System.DateTime> HoraCita { get; set; }
        public string Observacion { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual TrabajoCliente TrabajoCliente { get; set; }
    }
}
