//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfirmarPago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConfirmarPago()
        {
            this.DetallePagoProveedor = new HashSet<DetallePagoProveedor>();
        }
    
        public int IdConfirmarPago { get; set; }
        public Nullable<int> IdProgramarPago { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> MontoPorcentaje { get; set; }
        public Nullable<decimal> TotalApagar { get; set; }
    
        public virtual ProgramarPago ProgramarPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePagoProveedor> DetallePagoProveedor { get; set; }
    }
}
