//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracionPV
    {
        public int IdConfiguracionPV { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string TipoIncremento { get; set; }
        public Nullable<decimal> Incremento { get; set; }
        public string MonedaPorDefecto { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<int> PlazoCotizacion { get; set; }
        public string RegimenTributario { get; set; }
        public Nullable<decimal> IR { get; set; }
        public Nullable<decimal> IMI { get; set; }
        public Nullable<decimal> SERVICIOPROFESIONAL { get; set; }
    }
}
