//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfirmarMantenimiento
    {
        public int IdConfirmarMantenimiento { get; set; }
        public Nullable<int> IdMantenimientoFlota { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<System.DateTime> FechaRealizada { get; set; }
        public Nullable<System.TimeSpan> HoraRealizada { get; set; }
        public Nullable<int> KilometrajeActual { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<int> IdCotizacionMantenimiento { get; set; }
        public Nullable<int> IdMantenimientoOperacion { get; set; }
        public string Estado { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> IdFlotaVehicular { get; set; }
    
        public virtual MantenimientoFLota MantenimientoFLota { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual CotizarMantenimiento CotizarMantenimiento { get; set; }
        public virtual FlotaVehicular FlotaVehicular { get; set; }
        public virtual MantenimientoOperacion MantenimientoOperacion { get; set; }
    }
}
