//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consignacion
    {
        public int IdConsignacion { get; set; }
        public Nullable<int> IdBodega { get; set; }
        public Nullable<int> IdVendedor { get; set; }
        public Nullable<int> IdClienteSeguimiento { get; set; }
    
        public virtual Bodega Bodega { get; set; }
        public virtual ClienteSeguimiento ClienteSeguimiento { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
