//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorreoCarteraYCobro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CorreoCarteraYCobro()
        {
            this.DetalleCorreoCarteraYCobro = new HashSet<DetalleCorreoCarteraYCobro>();
        }
    
        public int IdCorreo { get; set; }
        public Nullable<int> IdEmpleadoEnvia { get; set; }
        public Nullable<int> IdClienteCobro { get; set; }
        public Nullable<System.DateTime> FechaEnvio { get; set; }
        public string Hora { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCorreoCarteraYCobro> DetalleCorreoCarteraYCobro { get; set; }
    }
}
