//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CotizacionCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CotizacionCompra()
        {
            this.ConsecutivoCotizacionCompra = new HashSet<ConsecutivoCotizacionCompra>();
            this.DetalleCotizacionCompra = new HashSet<DetalleCotizacionCompra>();
        }
    
        public int IdCotizacionCompra { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public Nullable<int> IdEmpleadoCotiza { get; set; }
        public Nullable<int> IdConceptoCotizacion { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdEmpleadoAprueba { get; set; }
        public string NumeroSerie { get; set; }
        public Nullable<System.DateTime> FechaCotizacion { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public Nullable<System.DateTime> Vigencia { get; set; }
        public string Descripcion { get; set; }
        public byte[] Formato { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string NombreDocumento { get; set; }
        public string NombreArchivo { get; set; }
        public Nullable<int> IdOrdenTrabajo { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual ConceptoCotizacion ConceptoCotizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsecutivoCotizacionCompra> ConsecutivoCotizacionCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCotizacionCompra> DetalleCotizacionCompra { get; set; }
    }
}
