//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CotizarMantenimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CotizarMantenimiento()
        {
            this.AprobarCotizacionMantenimiento = new HashSet<AprobarCotizacionMantenimiento>();
            this.ConfirmarMantenimiento = new HashSet<ConfirmarMantenimiento>();
            this.DetalleCotizarMantemiento = new HashSet<DetalleCotizarMantemiento>();
            this.FacturaReparacion = new HashSet<FacturaReparacion>();
        }
    
        public int IdCotizacionMantenimiento { get; set; }
        public Nullable<int> IdFlotaVehicular { get; set; }
        public Nullable<int> IdMantenimientoOperacion { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AprobarCotizacionMantenimiento> AprobarCotizacionMantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfirmarMantenimiento> ConfirmarMantenimiento { get; set; }
        public virtual FlotaVehicular FlotaVehicular { get; set; }
        public virtual MantenimientoOperacion MantenimientoOperacion { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCotizarMantemiento> DetalleCotizarMantemiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaReparacion> FacturaReparacion { get; set; }
    }
}
