//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CotizacionVenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CotizacionVenta()
        {
            this.DetalleCotizacionV = new HashSet<DetalleCotizacionV>();
            this.Reserva1 = new HashSet<Reserva>();
            this.PrefacturaVenta = new HashSet<PrefacturaVenta>();
        }
    
        public int IdCotizacion { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdVendedor { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public string Consecutivo { get; set; }
        public string SerieConsecutivo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdSegmento { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Estado { get; set; }
        public Nullable<decimal> TasaParalela { get; set; }
        public string Moneda { get; set; }
        public Nullable<int> Plazo { get; set; }
        public Nullable<bool> Reserva { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Segmento Segmento { get; set; }
        public virtual Vendedor Vendedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCotizacionV> DetalleCotizacionV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reserva1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrefacturaVenta> PrefacturaVenta { get; set; }
    }
}
