//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criterio_Proveedor
    {
        public int IdCriterioProveedor { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public string Periodo { get; set; }
        public Nullable<int> CriterioProveedor { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
    }
}
