//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaEmpleado
    {
        public int IdCuentaEmpleado { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public string NumeroCuenta { get; set; }
        public string Banco { get; set; }
        public string TipoMoneda { get; set; }
        public string Observacion { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
