//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaBanco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaBanco()
        {
            this.MinutaDeposito = new HashSet<MinutaDeposito>();
            this.MovimientoBancario = new HashSet<MovimientoBancario>();
            this.PagoRealizadoTesoreria = new HashSet<PagoRealizadoTesoreria>();
        }
    
        public int IdCuentaBanco { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public Nullable<int> IdTitular { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public string NoCuenta { get; set; }
        public string TipoMoneda { get; set; }
        public Nullable<decimal> SaldoCuenta { get; set; }
        public Nullable<System.DateTime> FechaElaboracion { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string TipoTitular { get; set; }
    
        public virtual Bancos Bancos { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MinutaDeposito> MinutaDeposito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoBancario> MovimientoBancario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoRealizadoTesoreria> PagoRealizadoTesoreria { get; set; }
    }
}
