//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosBancariosCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatosBancariosCliente()
        {
            this.ClienteBanco = new HashSet<ClienteBanco>();
        }
    
        public int IdDatosBancariosCliente { get; set; }
        public string Banco { get; set; }
        public string DireccionBanco { get; set; }
        public string NumeroCuenta { get; set; }
        public string Moneda { get; set; }
        public string SwiftCode { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClienteBanco> ClienteBanco { get; set; }
    }
}
