//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departamento()
        {
            this.CorreoDepartamento = new HashSet<CorreoDepartamento>();
            this.SolicitudCheque = new HashSet<SolicitudCheque>();
            this.FlotaSucursal = new HashSet<FlotaSucursal>();
            this.SucursalDepartamento = new HashSet<SucursalDepartamento>();
        }
    
        public int IdDepartamento { get; set; }
        public string ExtensionEncargado { get; set; }
        public string NombreDepartamento { get; set; }
        public string NombreEncargado { get; set; }
        public string CargoEncargado { get; set; }
        public string CelularEncargado { get; set; }
        public string Correo { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdDepartamentoSuperior { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CorreoDepartamento> CorreoDepartamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudCheque> SolicitudCheque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlotaSucursal> FlotaSucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SucursalDepartamento> SucursalDepartamento { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
