//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DescuentoxProntoPago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DescuentoxProntoPago()
        {
            this.DetalleDescuentoXProntoPAgo = new HashSet<DetalleDescuentoXProntoPAgo>();
        }
    
        public int IdDescuentoxPronto { get; set; }
        public string Consecutivo { get; set; }
        public Nullable<System.DateTime> FechaElaboracion { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdSerie { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Serie Serie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleDescuentoXProntoPAgo> DetalleDescuentoXProntoPAgo { get; set; }
    }
}
