//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DescripcionConceptoCaja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DescripcionConceptoCaja()
        {
            this.DetalleAnticipoCliente = new HashSet<DetalleAnticipoCliente>();
            this.DetalleReciboCajaChica = new HashSet<DetalleReciboCajaChica>();
            this.DetalleSolicitudPagoReciboCajaChica = new HashSet<DetalleSolicitudPagoReciboCajaChica>();
            this.ReciboCajaGeneral = new HashSet<ReciboCajaGeneral>();
        }
    
        public int IdDescripcionConceptoCaja { get; set; }
        public Nullable<int> IdEmpleadoDescribe { get; set; }
        public string NombreConcepto { get; set; }
        public Nullable<System.DateTime> FechaDescripcion { get; set; }
        public Nullable<int> IdCategoriaDescripcionConceptoCajaChica { get; set; }
    
        public virtual CategoriaDescripcionConceptoCajaChica CategoriaDescripcionConceptoCajaChica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleAnticipoCliente> DetalleAnticipoCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleReciboCajaChica> DetalleReciboCajaChica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleSolicitudPagoReciboCajaChica> DetalleSolicitudPagoReciboCajaChica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReciboCajaGeneral> ReciboCajaGeneral { get; set; }
    }
}
