//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleEquipos
    {
        public int IdDetalleEquipos { get; set; }
        public string TipoEquipo { get; set; }
        public string NombreEquipo { get; set; }
        public string Especificaciones { get; set; }
        public Nullable<int> IdEntregaEquipo { get; set; }
    
        public virtual EntregaEquipo EntregaEquipo { get; set; }
    }
}
