//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePagoRealizadoTesoreria
    {
        public int IdDetallePagoRealizadoTesoreria { get; set; }
        public Nullable<int> IdPagoRealizadoTesoreria { get; set; }
        public Nullable<int> IdSolicitudCheque { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual PagoRealizadoTesoreria PagoRealizadoTesoreria { get; set; }
        public virtual SolicitudCheque SolicitudCheque { get; set; }
    }
}
