//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleReciboCajaGeneral
    {
        public int IdDetalleReciboCajaGeneral { get; set; }
        public Nullable<int> IdReciboCajaGeneral { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public Nullable<decimal> MontoAbonado { get; set; }
        public Nullable<decimal> IR { get; set; }
        public Nullable<decimal> IMI { get; set; }
        public Nullable<decimal> TasaParalela { get; set; }
        public string MonedaTransaccion { get; set; }
        public string Tipo { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual ReciboCajaGeneral ReciboCajaGeneral { get; set; }
    }
}
