//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleNotasDebitoProveedor
    {
        public int IdDetalleDebitoProveedor { get; set; }
        public Nullable<int> IdNotasDebitoProveedor { get; set; }
        public Nullable<int> IdCatalogoConcepto { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> IVAExcento { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual ConceptoNotasDebitoProveedor ConceptoNotasDebitoProveedor { get; set; }
        public virtual NotasDebitoProveedor NotasDebitoProveedor { get; set; }
    }
}
