//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleNotasDebitoCredito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleNotasDebitoCredito()
        {
            this.NotasCreditoAplicadas = new HashSet<NotasCreditoAplicadas>();
        }
    
        public int IdDetalleNotasDebitoCredito { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public Nullable<int> IdCuentaContable { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<decimal> SubTotalNota { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<int> IdNotasCredito { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasCreditoAplicadas> NotasCreditoAplicadas { get; set; }
        public virtual NotasCredito NotasCredito { get; set; }
    }
}
