//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleTrasladoSolicitado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleTrasladoSolicitado()
        {
            this.DetalleTrasladoAprobado = new HashSet<DetalleTrasladoAprobado>();
        }
    
        public int IdDetalleTrasladoSolicitado { get; set; }
        public Nullable<int> IdSolicitudTraslado { get; set; }
        public Nullable<int> IdProduto { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleTrasladoAprobado> DetalleTrasladoAprobado { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual SolicitudTraslado SolicitudTraslado { get; set; }
    }
}
