//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetallePago()
        {
            this.NotasCreditoAplicadas = new HashSet<NotasCreditoAplicadas>();
            this.DetalleCheque = new HashSet<DetalleCheque>();
            this.DetalleEfectivo = new HashSet<DetalleEfectivo>();
            this.DetalleNotaDebitoRetencion = new HashSet<DetalleNotaDebitoRetencion>();
            this.DetalleReciboRetencion = new HashSet<DetalleReciboRetencion>();
            this.DetalleTransferencia = new HashSet<DetalleTransferencia>();
            this.DetalleTarjeta = new HashSet<DetalleTarjeta>();
        }
    
        public int IdDetallePago { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdCaja { get; set; }
        public Nullable<int> Cajero { get; set; }
        public Nullable<decimal> TasaParalela { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public Nullable<int> IdReciboCajaGeneral { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasCreditoAplicadas> NotasCreditoAplicadas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCheque> DetalleCheque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleEfectivo> DetalleEfectivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleNotaDebitoRetencion> DetalleNotaDebitoRetencion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleReciboRetencion> DetalleReciboRetencion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleTransferencia> DetalleTransferencia { get; set; }
        public virtual Factura Factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleTarjeta> DetalleTarjeta { get; set; }
    }
}
