//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleCompra()
        {
            this.DetalleCompraEliminados = new HashSet<DetalleCompraEliminados>();
            this.TotalLiquidacionCompra = new HashSet<TotalLiquidacionCompra>();
        }
    
        public int IdDetalleCompra { get; set; }
        public Nullable<int> IdCompra { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<int> Factor { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> FactorImpuesto { get; set; }
        public Nullable<decimal> FactorDescuento { get; set; }
        public Nullable<decimal> FactorIR { get; set; }
        public Nullable<decimal> FactorIMI { get; set; }
    
        public virtual Compra Compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCompraEliminados> DetalleCompraEliminados { get; set; }
        public virtual Producto Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TotalLiquidacionCompra> TotalLiquidacionCompra { get; set; }
    }
}
