//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCotizacionInsumo
    {
        public int IdDetalleCotizacionInsumo { get; set; }
        public Nullable<int> IdCotizacionOT { get; set; }
        public Nullable<int> IdServicio { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string TipoInsumo { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual CotizacionOT CotizacionOT { get; set; }
    }
}
