//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCompraEliminados
    {
        public int IdDetalleCompraEliminados { get; set; }
        public Nullable<int> IdDetalleCompra { get; set; }
        public Nullable<int> IdCompra { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual DetalleCompra DetalleCompra { get; set; }
    }
}
