//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFacturaReparacion
    {
        public int IdDetalleFacturaReparacion { get; set; }
        public Nullable<int> IdFacturaReparacion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> Iva { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<bool> Servicio { get; set; }
        public Nullable<bool> Producto { get; set; }
    
        public virtual FacturaReparacion FacturaReparacion { get; set; }
    }
}
