//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCotizarMantemiento
    {
        public int IdDetalleCotizar { get; set; }
        public Nullable<int> IdCotizacionMantenimiento { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<bool> servicio { get; set; }
        public Nullable<bool> producto { get; set; }
    
        public virtual CotizarMantenimiento CotizarMantenimiento { get; set; }
    }
}
