//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleTrabajoCliente
    {
        public int IdDetalleTrabajoCliente { get; set; }
        public Nullable<int> IdTrabajoCliente { get; set; }
        public Nullable<int> IdMantenimiento { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual TrabajoCliente TrabajoCliente { get; set; }
    }
}
