//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleSolicitudGO
    {
        public int IdDetalleSolicitudGO { get; set; }
        public Nullable<int> IdSolicitudGastosOperativos { get; set; }
        public Nullable<int> IdGastosOperativos { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> IR { get; set; }
        public Nullable<decimal> IMI { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
    
        public virtual GastosOperativos GastosOperativos { get; set; }
        public virtual SolicitudGastosOperativos SolicitudGastosOperativos { get; set; }
    }
}
