//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleTransferencia
    {
        public int IdDetalleTransferencia { get; set; }
        public Nullable<int> IdDetallePago { get; set; }
        public Nullable<decimal> MontoTransferido { get; set; }
        public string TipoMoneda { get; set; }
        public string Banco { get; set; }
        public string NumeroReferencia { get; set; }
        public Nullable<System.DateTime> FechaTransferencia { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public Nullable<int> IdCuenta { get; set; }
    
        public virtual DetallePago DetallePago { get; set; }
    }
}
