//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleTraslado
    {
        public int IdDetalleTraslado { get; set; }
        public Nullable<int> IdTraslado { get; set; }
        public Nullable<int> IdProduto { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> CantidadEnviada { get; set; }
        public Nullable<decimal> CantidadRecibida { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Traslado Traslado { get; set; }
    }
}
