//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesImpuestos
    {
        public int IdDetallesImpuestos { get; set; }
        public Nullable<int> IdCompra { get; set; }
        public Nullable<int> IdServLiquidacion { get; set; }
        public Nullable<decimal> Flete { get; set; }
        public Nullable<decimal> SEGURO { get; set; }
        public Nullable<decimal> OG { get; set; }
        public Nullable<decimal> DAI { get; set; }
        public Nullable<decimal> ISC { get; set; }
        public Nullable<decimal> TSIM { get; set; }
        public Nullable<decimal> SPE { get; set; }
        public Nullable<decimal> SSA { get; set; }
        public Nullable<decimal> AGEN { get; set; }
        public Nullable<decimal> ALMAC { get; set; }
        public Nullable<decimal> TRAMCNTR { get; set; }
        public Nullable<decimal> EPNMOV { get; set; }
        public Nullable<decimal> EPNSCAN { get; set; }
        public Nullable<decimal> OtrosGastos { get; set; }
        public string Estado { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual ServiciosImportacion ServiciosImportacion { get; set; }
    }
}
