//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleRetencionesProveedor
    {
        public int IdRetencionesDetalle { get; set; }
        public Nullable<int> IdRetencionesProveedor { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> IR { get; set; }
        public Nullable<decimal> IMI { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual RetencionesProveedor RetencionesProveedor { get; set; }
    }
}
