//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePagoProveedor
    {
        public int IdDetallePago { get; set; }
        public Nullable<int> IdConfirmarPago { get; set; }
        public Nullable<int> IdBanco { get; set; }
        public string Tipo { get; set; }
        public string NoDocumento { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Moneda { get; set; }
    
        public virtual Bancos Bancos { get; set; }
        public virtual ConfirmarPago ConfirmarPago { get; set; }
    }
}
