//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleServiciosImportacion
    {
        public int IdDetalleServiciosImportacion { get; set; }
        public Nullable<int> IdServiciosImportacion { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Concepto { get; set; }
        public string Factura { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
        public virtual ServiciosImportacion ServiciosImportacion { get; set; }
    }
}
