//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleAsignarProductos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleAsignarProductos()
        {
            this.Insumos = new HashSet<Insumos>();
        }
    
        public int IdDetalleAsignarProductos { get; set; }
        public Nullable<int> IdAsignarProductos { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> CatidadEnviada { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual AsignarProductos AsignarProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Insumos> Insumos { get; set; }
    }
}
