//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePreFacturaOT
    {
        public int IdDetallePreFacturaOT { get; set; }
        public Nullable<int> IdPreFacturaOT { get; set; }
        public Nullable<int> IdMantenimiento { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> IdTrabajoExterno { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public Nullable<decimal> CostoUnitario { get; set; }
        public Nullable<decimal> Iva { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<decimal> IvaExcento { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual MantenimientoOrdenTrabajo MantenimientoOrdenTrabajo { get; set; }
        public virtual PreFacturaOT PreFacturaOT { get; set; }
        public virtual TrabajosExternos TrabajosExternos { get; set; }
    }
}
