//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleTarjeta
    {
        public int IdDetalleTarjeta { get; set; }
        public string Baucher { get; set; }
        public string Banco { get; set; }
        public string Moneda { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> IdDetallePago { get; set; }
        public Nullable<int> IdBanco { get; set; }
    
        public virtual DetallePago DetallePago { get; set; }
    }
}
