//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleReciboRetencion
    {
        public int IdDetalleReciboFactura { get; set; }
        public Nullable<int> IdDetallePago { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public Nullable<decimal> IR { get; set; }
        public Nullable<decimal> IMI { get; set; }
        public Nullable<decimal> MontoIR { get; set; }
        public Nullable<decimal> MontoIMI { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public string Moneda { get; set; }
    
        public virtual DetallePago DetallePago { get; set; }
        public virtual Factura Factura { get; set; }
    }
}
