//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleDevolucionCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetalleDevolucionCompra()
        {
            this.DetalleProductoDevolucionCompra = new HashSet<DetalleProductoDevolucionCompra>();
        }
    
        public int IdDetalleDevolucionCompra { get; set; }
        public Nullable<int> IdDevolucionCompra { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string TipoProd { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual DevolucionCompra DevolucionCompra { get; set; }
        public virtual Producto Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleProductoDevolucionCompra> DetalleProductoDevolucionCompra { get; set; }
    }
}
