//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevolucionCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DevolucionCompra()
        {
            this.DetalleDevolucionCompra = new HashSet<DetalleDevolucionCompra>();
        }
    
        public int IdDevolucionCompra { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public string Consecutivo { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> IdCompra { get; set; }
        public Nullable<int> IdBodega { get; set; }
        public Nullable<System.DateTime> FechaDevolucion { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public string SerieConsecutivo { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string TipoDevolucion { get; set; }
    
        public virtual Compra Compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleDevolucionCompra> DetalleDevolucionCompra { get; set; }
    }
}
