//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistribucionGastosOperativos
    {
        public int IdDistribucionGastosOperativos { get; set; }
        public Nullable<int> IdSolicitudGastosOperativos { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual SolicitudGastosOperativos SolicitudGastosOperativos { get; set; }
    }
}
