//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentoSoporte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentoSoporte()
        {
            this.RequisitosProcesamiento = new HashSet<RequisitosProcesamiento>();
            this.DocumentoDesvinculacion = new HashSet<DocumentoDesvinculacion>();
        }
    
        public int IdDocSoporte { get; set; }
        public string NombreArchivo { get; set; }
        public byte[] Contenido { get; set; }
        public string NombreDocumento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitosProcesamiento> RequisitosProcesamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoDesvinculacion> DocumentoDesvinculacion { get; set; }
    }
}
