//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emergencia
    {
        public int IdEmergencia { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public string NombrePersona { get; set; }
        public string Parentezco { get; set; }
        public string TelefonoEmergencia1 { get; set; }
        public string TelefonoEmergencia2 { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
