//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadoPuesto
    {
        public int IdEmpleadoPuesto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Observacion { get; set; }
        public Nullable<bool> Estado { get; set; }
        public int IdEmpleado { get; set; }
        public Nullable<int> IdPuesto { get; set; }
        public string MovimientoEstado { get; set; }
        public Nullable<decimal> Salarionuevo { get; set; }
        public string TipoMoneda { get; set; }
        public string TipoMovimiento { get; set; }
        public string PeriodoPrueba { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Puesto Puesto { get; set; }
    }
}
