//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadosPreFacturaInternaOT
    {
        public int IdEmpleadosPreFacturaInternaOT { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdConcepto { get; set; }
        public Nullable<int> IdPrefacturaInternaOT { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> Porcentaje { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string Moneda { get; set; }
        public Nullable<decimal> TasaCambio { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual PreFacturaInternaOT PreFacturaInternaOT { get; set; }
    }
}
