//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleado()
        {
            this.AsignacionCajaChica = new HashSet<AsignacionCajaChica>();
            this.MinutaDeposito = new HashSet<MinutaDeposito>();
            this.PagoRealizadoTesoreria = new HashSet<PagoRealizadoTesoreria>();
            this.ReciboCajaChica = new HashSet<ReciboCajaChica>();
            this.SolicitudCheque = new HashSet<SolicitudCheque>();
            this.SolicitudPagoCajaChica = new HashSet<SolicitudPagoCajaChica>();
            this.SolicitudReembolsoCajaChica = new HashSet<SolicitudReembolsoCajaChica>();
            this.AprobarCotizacionMantenimiento = new HashSet<AprobarCotizacionMantenimiento>();
            this.Mecanicos = new HashSet<Mecanicos>();
            this.AnulacionCompra = new HashSet<AnulacionCompra>();
            this.AnulacionTraslado = new HashSet<AnulacionTraslado>();
            this.Compra = new HashSet<Compra>();
            this.Compra1 = new HashSet<Compra>();
            this.DescuentoxProntoPago = new HashSet<DescuentoxProntoPago>();
            this.DespachoFactura = new HashSet<DespachoFactura>();
            this.PermisoEmpleadoBodega = new HashSet<PermisoEmpleadoBodega>();
            this.ProcesamientoCreditoCliente = new HashSet<ProcesamientoCreditoCliente>();
            this.ProcesamientoCreditoCliente1 = new HashSet<ProcesamientoCreditoCliente>();
            this.ReciboCajaGeneral = new HashSet<ReciboCajaGeneral>();
            this.Reserva = new HashSet<Reserva>();
            this.ReversionDocumento = new HashSet<ReversionDocumento>();
            this.SolicitudTraslado = new HashSet<SolicitudTraslado>();
            this.SolicitudTraslado1 = new HashSet<SolicitudTraslado>();
            this.Traslado = new HashSet<Traslado>();
            this.Vendedor = new HashSet<Vendedor>();
            this.Accidente = new HashSet<Accidente>();
            this.Adelanto = new HashSet<Adelanto>();
            this.AplicacionEmpleado = new HashSet<AplicacionEmpleado>();
            this.Asistencia = new HashSet<Asistencia>();
            this.BajaPersonal = new HashSet<BajaPersonal>();
            this.ContratoLaboral = new HashSet<ContratoLaboral>();
            this.CuentaEmpleado = new HashSet<CuentaEmpleado>();
            this.DesvinculacionPersonal = new HashSet<DesvinculacionPersonal>();
            this.Documento = new HashSet<Documento>();
            this.Emergencia = new HashSet<Emergencia>();
            this.CotizacionCompra = new HashSet<CotizacionCompra>();
            this.EmpleadoPuesto = new HashSet<EmpleadoPuesto>();
            this.EmpleadosPreFacturaInternaOT = new HashSet<EmpleadosPreFacturaInternaOT>();
            this.EvaluacionBaja = new HashSet<EvaluacionBaja>();
            this.Incidente = new HashSet<Incidente>();
            this.Liquidacion = new HashSet<Liquidacion>();
            this.NivelAcademico = new HashSet<NivelAcademico>();
            this.Nomina = new HashSet<Nomina>();
            this.PermisoEmpleado = new HashSet<PermisoEmpleado>();
            this.SolicitudPermisoSistema = new HashSet<SolicitudPermisoSistema>();
            this.UbicacionEmpleado = new HashSet<UbicacionEmpleado>();
            this.Usuario = new HashSet<Usuario>();
            this.EntregaEquipo = new HashSet<EntregaEquipo>();
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int IdEmpleado { get; set; }
        public string Codigo { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Cedula { get; set; }
        public string Sexo { get; set; }
        public string Nacionalidad { get; set; }
        public string Ciudad { get; set; }
        public string Direccion { get; set; }
        public byte[] Foto { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Correo { get; set; }
        public string TipoSangre { get; set; }
        public Nullable<System.DateTime> LicenciaVence { get; set; }
        public string CategoriaLicencia { get; set; }
        public string LicenciaNumero { get; set; }
        public string PolizaLicencia { get; set; }
        public Nullable<System.DateTime> PolizaVence { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public bool Estado { get; set; }
        public string Inss { get; set; }
        public Nullable<decimal> SalarioMensual { get; set; }
        public string TipoMoneda { get; set; }
        public string Celular1 { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> IdEmpleadoSuperior { get; set; }
        public Nullable<int> SemanasCotizadas { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionCajaChica> AsignacionCajaChica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MinutaDeposito> MinutaDeposito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoRealizadoTesoreria> PagoRealizadoTesoreria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReciboCajaChica> ReciboCajaChica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudCheque> SolicitudCheque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudPagoCajaChica> SolicitudPagoCajaChica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudReembolsoCajaChica> SolicitudReembolsoCajaChica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AprobarCotizacionMantenimiento> AprobarCotizacionMantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mecanicos> Mecanicos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnulacionCompra> AnulacionCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnulacionTraslado> AnulacionTraslado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compra1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DescuentoxProntoPago> DescuentoxProntoPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DespachoFactura> DespachoFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermisoEmpleadoBodega> PermisoEmpleadoBodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcesamientoCreditoCliente> ProcesamientoCreditoCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcesamientoCreditoCliente> ProcesamientoCreditoCliente1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReciboCajaGeneral> ReciboCajaGeneral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reserva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReversionDocumento> ReversionDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudTraslado> SolicitudTraslado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudTraslado> SolicitudTraslado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Traslado> Traslado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vendedor> Vendedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accidente> Accidente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adelanto> Adelanto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AplicacionEmpleado> AplicacionEmpleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asistencia> Asistencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BajaPersonal> BajaPersonal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContratoLaboral> ContratoLaboral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaEmpleado> CuentaEmpleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DesvinculacionPersonal> DesvinculacionPersonal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documento> Documento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emergencia> Emergencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CotizacionCompra> CotizacionCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpleadoPuesto> EmpleadoPuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpleadosPreFacturaInternaOT> EmpleadosPreFacturaInternaOT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluacionBaja> EvaluacionBaja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incidente> Incidente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Liquidacion> Liquidacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NivelAcademico> NivelAcademico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nomina> Nomina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermisoEmpleado> PermisoEmpleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudPermisoSistema> SolicitudPermisoSistema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UbicacionEmpleado> UbicacionEmpleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntregaEquipo> EntregaEquipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
