//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.CatalogoCuenta = new HashSet<CatalogoCuenta>();
            this.ConfiguracionFIN = new HashSet<ConfiguracionFIN>();
            this.PagoRealizadoTesoreria = new HashSet<PagoRealizadoTesoreria>();
            this.ConfiguracionRRHH = new HashSet<ConfiguracionRRHH>();
            this.ContactoEmpresa = new HashSet<ContactoEmpresa>();
            this.Departamento = new HashSet<Departamento>();
            this.BitacoraUsuario = new HashSet<BitacoraUsuario>();
            this.SistemaEmpresa = new HashSet<SistemaEmpresa>();
            this.Horario = new HashSet<Horario>();
        }
    
        public int IdEmpresa { get; set; }
        public string NombreEmpresa { get; set; }
        public string Ruc { get; set; }
        public string Direccion { get; set; }
        public string Giro { get; set; }
        public byte[] Logo { get; set; }
        public string PaginaWeb { get; set; }
        public string Telefono { get; set; }
        public string Eslogan { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Celular1 { get; set; }
        public string Celular2 { get; set; }
        public Nullable<int> IdPais { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogoCuenta> CatalogoCuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfiguracionFIN> ConfiguracionFIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoRealizadoTesoreria> PagoRealizadoTesoreria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfiguracionRRHH> ConfiguracionRRHH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactoEmpresa> ContactoEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departamento> Departamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraUsuario> BitacoraUsuario { get; set; }
        public virtual Pais Pais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SistemaEmpresa> SistemaEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horario> Horario { get; set; }
    }
}
