//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstacionesProduccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EstacionesProduccion()
        {
            this.AsignarTecnicosOrdenProduccion = new HashSet<AsignarTecnicosOrdenProduccion>();
        }
    
        public int IdEstacionesProduccion { get; set; }
        public string NombreEstacion { get; set; }
        public Nullable<decimal> CantidadMax { get; set; }
        public Nullable<int> IdUbicacion { get; set; }
        public string Descripcion { get; set; }
        public string TipoMoneda { get; set; }
        public Nullable<decimal> Tasa { get; set; }
        public Nullable<decimal> CostoHora { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignarTecnicosOrdenProduccion> AsignarTecnicosOrdenProduccion { get; set; }
        public virtual UbicacionFabrica UbicacionFabrica { get; set; }
    }
}
