//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluacionBaja
    {
        public int IdEvaluacionBaja { get; set; }
        public Nullable<int> IdBajaPersonal { get; set; }
        public Nullable<int> IdLLenadoPor { get; set; }
        public string Puntualidad { get; set; }
        public string UsoUniforme { get; set; }
        public string Informes { get; set; }
        public string Equipos { get; set; }
        public string AreaTrabajo { get; set; }
        public string CumplimientoOrientaciones { get; set; }
        public string HigieneYLimpieza { get; set; }
        public string Manipulacion { get; set; }
        public string ConCompañerosLaborales { get; set; }
        public string ConJefeInmediato { get; set; }
        public string ConPersonalSuperior { get; set; }
        public string ConClientes { get; set; }
        public string ConocimientoBasico { get; set; }
        public string NivelAprendizake { get; set; }
        public string IniciativaCreatividad { get; set; }
        public string Dinamismo { get; set; }
        public string CumplimientoObjetivos { get; set; }
        public string IncidePositivamente { get; set; }
        public string NivelConfianza { get; set; }
        public Nullable<int> IdDesvinculacion { get; set; }
    
        public virtual BajaPersonal BajaPersonal { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
