//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaReparacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacturaReparacion()
        {
            this.DetalleFacturaReparacion = new HashSet<DetalleFacturaReparacion>();
        }
    
        public int IdFacturaReparacion { get; set; }
        public Nullable<int> IdPrefacturaOT { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
        public string NoOrdenTrabajo { get; set; }
        public string NoFactura { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public string Proveedor { get; set; }
        public string TipoMoneda { get; set; }
        public string TipoPago { get; set; }
        public string TipoMantenimiento { get; set; }
        public string NivelReparacion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public string Consecutivo { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<int> IdFlotaVehicular { get; set; }
        public Nullable<int> IdCotizacionAporbada { get; set; }
        public string SerieConsecutivo { get; set; }
        public Nullable<int> IdSucursalDepartamento { get; set; }
        public Nullable<int> IdDepartamneto { get; set; }
        public string Sitema { get; set; }
    
        public virtual CotizarMantenimiento CotizarMantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFacturaReparacion> DetalleFacturaReparacion { get; set; }
        public virtual FlotaVehicular FlotaVehicular { get; set; }
        public virtual SucursalDepartamento SucursalDepartamento { get; set; }
        public virtual PreFacturaOT PreFacturaOT { get; set; }
    }
}
