//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlotaVehicular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlotaVehicular()
        {
            this.AccesorioFlota = new HashSet<AccesorioFlota>();
            this.Combustible1 = new HashSet<Combustible>();
            this.ConfirmarMantenimiento = new HashSet<ConfirmarMantenimiento>();
            this.CotizarMantenimiento = new HashSet<CotizarMantenimiento>();
            this.FacturaReparacion = new HashSet<FacturaReparacion>();
            this.FlotaSucursal = new HashSet<FlotaSucursal>();
            this.FlotaCliente = new HashSet<FlotaCliente>();
            this.ImagenFlota = new HashSet<ImagenFlota>();
            this.OrdenTrabajo = new HashSet<OrdenTrabajo>();
            this.CotizacionOT = new HashSet<CotizacionOT>();
        }
    
        public int IdFlota { get; set; }
        public Nullable<int> IdPropietario { get; set; }
        public string TipoCliente { get; set; }
        public string Placa { get; set; }
        public string Color { get; set; }
        public string Año { get; set; }
        public string Vim { get; set; }
        public string Motor { get; set; }
        public string Tonelaje { get; set; }
        public string Cilindro { get; set; }
        public string Pasajero { get; set; }
        public string Combustible { get; set; }
        public Nullable<int> TipoVehiculo { get; set; }
        public string Circulacion { get; set; }
        public Nullable<System.DateTime> FechaEmision { get; set; }
        public string Poliza { get; set; }
        public Nullable<System.DateTime> SeguroVence { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> IdModelo { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccesorioFlota> AccesorioFlota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Combustible> Combustible1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfirmarMantenimiento> ConfirmarMantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CotizarMantenimiento> CotizarMantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaReparacion> FacturaReparacion { get; set; }
        public virtual FlotaModelo FlotaModelo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlotaSucursal> FlotaSucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlotaCliente> FlotaCliente { get; set; }
        public virtual TipoVehiculo TipoVehiculo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagenFlota> ImagenFlota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenTrabajo> OrdenTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CotizacionOT> CotizacionOT { get; set; }
    }
}
