//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlotaCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlotaCliente()
        {
            this.TrabajoCliente = new HashSet<TrabajoCliente>();
        }
    
        public int IdFlotaCliente { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdFlotaVehicular { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual FlotaVehicular FlotaVehicular { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrabajoCliente> TrabajoCliente { get; set; }
    }
}
