//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlotaSucursal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FlotaSucursal()
        {
            this.AsignarConductoresVehiculos = new HashSet<AsignarConductoresVehiculos>();
            this.DetalleActivacionFlota = new HashSet<DetalleActivacionFlota>();
            this.DocumentosDelVehiculo = new HashSet<DocumentosDelVehiculo>();
            this.MantenimientoFLota = new HashSet<MantenimientoFLota>();
        }
    
        public int IdFlotaSucursal { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public Nullable<int> IdFlotaVehicular { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignarConductoresVehiculos> AsignarConductoresVehiculos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleActivacionFlota> DetalleActivacionFlota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentosDelVehiculo> DocumentosDelVehiculo { get; set; }
        public virtual FlotaVehicular FlotaVehicular { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MantenimientoFLota> MantenimientoFLota { get; set; }
        public virtual Departamento Departamento { get; set; }
    }
}
