//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HerramientaPuesto
    {
        public int IdHerramientaPuesto { get; set; }
        public string HerramientasPuesto { get; set; }
        public Nullable<int> IdPuesto { get; set; }
    
        public virtual Puesto Puesto { get; set; }
    }
}
