//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentificadorVehiculo
    {
        public int IdIdentificadorVehiculo { get; set; }
        public string Placa { get; set; }
        public string Circulacion { get; set; }
        public Nullable<System.DateTime> VencimientoCirculacion { get; set; }
        public string Seguro { get; set; }
        public Nullable<System.DateTime> VencimientoSeguro { get; set; }
        public Nullable<int> IdIdentificador { get; set; }
    
        public virtual IdentificadorProducto IdentificadorProducto { get; set; }
    }
}
