//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenesVehiculoOT
    {
        public int IdImagenVehiculoOT { get; set; }
        public Nullable<int> IdOrdenTrabajo { get; set; }
        public byte[] Imagen { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual OrdenTrabajo OrdenTrabajo { get; set; }
    }
}
