//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insumos
    {
        public int IdInsumo { get; set; }
        public Nullable<int> IdAsignarProductos { get; set; }
        public Nullable<int> IdDetalleAsignar { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual AsignarProductos AsignarProductos { get; set; }
        public virtual DetalleAsignarProductos DetalleAsignarProductos { get; set; }
    }
}
