//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liquidacion
    {
        public int idLiquidacion { get; set; }
        public int idEmpleado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.DateTime> fechaSalida { get; set; }
        public Nullable<int> diasDevengados { get; set; }
        public Nullable<decimal> salarioDevengado { get; set; }
        public Nullable<int> diasAguinaldo { get; set; }
        public Nullable<decimal> decimo { get; set; }
        public Nullable<decimal> saldoVacaciones { get; set; }
        public Nullable<decimal> pagoVacaciones { get; set; }
        public Nullable<int> aniosPagados { get; set; }
        public Nullable<int> mesesPagados { get; set; }
        public Nullable<int> diasPagados { get; set; }
        public Nullable<decimal> pagoAnios { get; set; }
        public Nullable<decimal> pagoMeses { get; set; }
        public Nullable<decimal> pagoDias { get; set; }
        public Nullable<decimal> indemnizacion { get; set; }
        public Nullable<decimal> totalIngreso { get; set; }
        public Nullable<decimal> inss { get; set; }
        public Nullable<decimal> ir { get; set; }
        public Nullable<decimal> cuentasCobrar { get; set; }
        public Nullable<decimal> diasNoLaborados { get; set; }
        public Nullable<decimal> totalDeduccion { get; set; }
        public Nullable<decimal> inssPatronal { get; set; }
        public Nullable<decimal> inatec { get; set; }
        public string estado { get; set; }
        public Nullable<decimal> bonificacion { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> altaComision { get; set; }
        public Nullable<decimal> promComision { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
