//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MantenimientoOrdenTrabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MantenimientoOrdenTrabajo()
        {
            this.DetallePreFacturaInternaOT = new HashSet<DetallePreFacturaInternaOT>();
            this.DetallePreFacturaOT = new HashSet<DetallePreFacturaOT>();
        }
    
        public int IdMantenimientoOrdenTrabajo { get; set; }
        public Nullable<int> IdOrdenTrabajo { get; set; }
        public Nullable<int> IdMantenimiento { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> Ganancia { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<bool> Cargado { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePreFacturaInternaOT> DetallePreFacturaInternaOT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePreFacturaOT> DetallePreFacturaOT { get; set; }
        public virtual Mantenimiento Mantenimiento { get; set; }
        public virtual OrdenTrabajo OrdenTrabajo { get; set; }
    }
}
