//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mantenimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mantenimiento()
        {
            this.DetalleMantenimiento = new HashSet<DetalleMantenimiento>();
            this.DetalleServicioCotizacionOT = new HashSet<DetalleServicioCotizacionOT>();
            this.MantenimientoOrdenTrabajo = new HashSet<MantenimientoOrdenTrabajo>();
            this.TrabajosExternos = new HashSet<TrabajosExternos>();
        }
    
        public int IdMantenimiento { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string TipoVehiculo { get; set; }
        public string Tonelaje { get; set; }
        public string Sistema { get; set; }
        public string TipoMantenimiento { get; set; }
        public Nullable<decimal> Duracion { get; set; }
        public Nullable<decimal> TasaCambio { get; set; }
        public string Moneda { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> FactorGanancia { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public Nullable<decimal> FactorGananciaMin { get; set; }
        public Nullable<decimal> PrecioVentaMin { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleMantenimiento> DetalleMantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleServicioCotizacionOT> DetalleServicioCotizacionOT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MantenimientoOrdenTrabajo> MantenimientoOrdenTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrabajosExternos> TrabajosExternos { get; set; }
    }
}
