//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MantenimientoFLota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MantenimientoFLota()
        {
            this.ConfirmarMantenimiento = new HashSet<ConfirmarMantenimiento>();
            this.DetalleMantenimientoFlota = new HashSet<DetalleMantenimientoFlota>();
        }
    
        public int IdMantenimientoFLota { get; set; }
        public Nullable<int> IdFlotaSucursal { get; set; }
        public Nullable<int> ParametroAvisoFecha { get; set; }
        public Nullable<System.DateTime> FechaActual { get; set; }
        public Nullable<System.DateTime> FechaProxima { get; set; }
        public Nullable<int> ParametroAvisoHora { get; set; }
        public Nullable<int> HorometroActual { get; set; }
        public Nullable<int> HorometroFinal { get; set; }
        public Nullable<int> ParametroAvisoKilometraje { get; set; }
        public Nullable<int> KilometrajeActual { get; set; }
        public Nullable<int> KilometrajeFinal { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfirmarMantenimiento> ConfirmarMantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleMantenimientoFlota> DetalleMantenimientoFlota { get; set; }
        public virtual FlotaSucursal FlotaSucursal { get; set; }
    }
}
