//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MantenimientoOperacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MantenimientoOperacion()
        {
            this.ConfirmarMantenimiento = new HashSet<ConfirmarMantenimiento>();
            this.CotizarMantenimiento = new HashSet<CotizarMantenimiento>();
            this.DetalleMantenimientoFlota = new HashSet<DetalleMantenimientoFlota>();
            this.DetalleMantenimientoOperacion = new HashSet<DetalleMantenimientoOperacion>();
        }
    
        public int IdMantenimientoOperacion { get; set; }
        public string Categoria { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string TipoVehiculo { get; set; }
        public Nullable<decimal> Tonelaje { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> ParametroKilometraje { get; set; }
        public Nullable<decimal> ParametroHorometro { get; set; }
        public Nullable<int> ParametroFecha { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfirmarMantenimiento> ConfirmarMantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CotizarMantenimiento> CotizarMantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleMantenimientoFlota> DetalleMantenimientoFlota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleMantenimientoOperacion> DetalleMantenimientoOperacion { get; set; }
    }
}
