//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mecanicos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mecanicos()
        {
            this.MecanicosEstacionTrabajo = new HashSet<MecanicosEstacionTrabajo>();
            this.MecanicosVehiculoProceso = new HashSet<MecanicosVehiculoProceso>();
        }
    
        public int IdMecanico { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public string Categoria { get; set; }
        public string Ubicacion { get; set; }
        public string Puesto { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MecanicosEstacionTrabajo> MecanicosEstacionTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MecanicosVehiculoProceso> MecanicosVehiculoProceso { get; set; }
    }
}
