//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MinutaDeposito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MinutaDeposito()
        {
            this.MovimientoBancario = new HashSet<MovimientoBancario>();
        }
    
        public int IdMinutaDeposito { get; set; }
        public Nullable<int> IdEmpleadoRealiza { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public Nullable<int> IdCuentaBanco { get; set; }
        public Nullable<int> IdConceptoMinutaDeposito { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public Nullable<int> idAperturaDia { get; set; }
        public Nullable<int> IdCierreDia { get; set; }
        public string Consecutivo { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string TipoPago { get; set; }
        public string NoVaucher { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> InteresBancario { get; set; }
        public Nullable<decimal> ComisionBancaria { get; set; }
        public string Observacion { get; set; }
        public Nullable<decimal> MontoTotal { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string SerieConsecutivo { get; set; }
    
        public virtual ConceptoMinutaDeposito ConceptoMinutaDeposito { get; set; }
        public virtual CuentaBanco CuentaBanco { get; set; }
        public virtual CierreDia CierreDia { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoBancario> MovimientoBancario { get; set; }
        public virtual AperturaDia AperturaDia { get; set; }
    }
}
