//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientosEntreOrdenesTrabajoDetalle
    {
        public int IdMovimientosEntreOrdenesTrabajoDetalle { get; set; }
        public Nullable<int> IdMovimientosEntreOrdenesTrabajo { get; set; }
        public Nullable<int> IdTrabajoExterno { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual MovimientosEntreOrdenesTrabajo MovimientosEntreOrdenesTrabajo { get; set; }
    }
}
