//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoBancario
    {
        public int IdMovimientoBancario { get; set; }
        public Nullable<int> IdCuentaBanco { get; set; }
        public Nullable<int> IdPagoRealizadoTesoreria { get; set; }
        public Nullable<int> IdMinutaDeposito { get; set; }
        public string TipoMovimiento { get; set; }
        public Nullable<decimal> SaldoAnterior { get; set; }
        public Nullable<decimal> SaldoActual { get; set; }
        public Nullable<decimal> SaldoDiferencial { get; set; }
        public string TipoAccion { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual CuentaBanco CuentaBanco { get; set; }
        public virtual MinutaDeposito MinutaDeposito { get; set; }
        public virtual PagoRealizadoTesoreria PagoRealizadoTesoreria { get; set; }
    }
}
