//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientosEntreOrdenesTrabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MovimientosEntreOrdenesTrabajo()
        {
            this.MovimientosEntreOrdenesTrabajoDetalle = new HashSet<MovimientosEntreOrdenesTrabajoDetalle>();
        }
    
        public int IdMovimientosEntreOrdenesTrabajo { get; set; }
        public Nullable<int> IdOrdenSalida { get; set; }
        public Nullable<int> IdOrdenEntrada { get; set; }
        public Nullable<int> IdEmpleadoRealiza { get; set; }
        public Nullable<System.DateTime> FechaRealiza { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientosEntreOrdenesTrabajoDetalle> MovimientosEntreOrdenesTrabajoDetalle { get; set; }
    }
}
