//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasDebitoCredito
    {
        public int IdNotasDebitoCredito { get; set; }
        public Nullable<int> IdEmpleadoSolicita { get; set; }
        public Nullable<int> IdEmpleadoAprueba { get; set; }
        public Nullable<int> IdBeneficiario { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Consecutivo { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public string TipoNota { get; set; }
        public string TipoBeneficiario { get; set; }
        public string AplicaA { get; set; }
        public string EnConceptoDe { get; set; }
        public string Observacion { get; set; }
        public Nullable<bool> AplicaACuentasContables { get; set; }
        public string Estado { get; set; }
    }
}
