//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasCreditoAplicadas
    {
        public int IdNotasCreditoAplicadas { get; set; }
        public Nullable<int> IdDetalleNotasDebitoCredito { get; set; }
        public Nullable<int> IdDetallePago { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Tipo { get; set; }
        public string Estado { get; set; }
    
        public virtual DetalleNotasDebitoCredito DetalleNotasDebitoCredito { get; set; }
        public virtual DetallePago DetallePago { get; set; }
    }
}
