//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasCredito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotasCredito()
        {
            this.DetalleNotasDebitoCredito = new HashSet<DetalleNotasDebitoCredito>();
        }
    
        public int IdNotasCredito { get; set; }
        public Nullable<int> IdEmpleadoSolicita { get; set; }
        public Nullable<int> IdEmpleadoAprueba { get; set; }
        public Nullable<int> IdBeneficiario { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Consecutivo { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public string TipoBeneficiario { get; set; }
        public string AplicaA { get; set; }
        public string Observacion { get; set; }
        public Nullable<bool> AplicaACuentasContables { get; set; }
        public string Estado { get; set; }
        public string SerieConsecutivo { get; set; }
        public Nullable<int> IdConcepto { get; set; }
        public string Moneda { get; set; }
    
        public virtual ConceptoNotaCredito ConceptoNotaCredito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleNotasDebitoCredito> DetalleNotasDebitoCredito { get; set; }
    }
}
