//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaCreditoProveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotaCreditoProveedor()
        {
            this.DetalleNotaCreditoProveedor = new HashSet<DetalleNotaCreditoProveedor>();
        }
    
        public int IdNotaCreditoProveedor { get; set; }
        public Nullable<int> IdEmpleadoSolicita { get; set; }
        public Nullable<int> IdEmpleadoAprueba { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Consecutivo { get; set; }
        public string NoNotaCredito { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public Nullable<System.DateTime> FechaNotaCrédito { get; set; }
        public string TipoBeneficiario { get; set; }
        public string AplicaA { get; set; }
        public string Observacion { get; set; }
        public Nullable<bool> AplicaACuentasContables { get; set; }
        public string Estado { get; set; }
        public string SerieConsecutivo { get; set; }
        public string TipoMoneda { get; set; }
        public Nullable<int> IdConcepto { get; set; }
    
        public virtual ConceptoNotaCreditoProveedor ConceptoNotaCreditoProveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleNotaCreditoProveedor> DetalleNotaCreditoProveedor { get; set; }
    }
}
