//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasDebito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotasDebito()
        {
            this.DetalleNotasDebito = new HashSet<DetalleNotasDebito>();
            this.DetalleNotaDebitoRetencion = new HashSet<DetalleNotaDebitoRetencion>();
            this.DetalleReciboCajaGeneralNota = new HashSet<DetalleReciboCajaGeneralNota>();
        }
    
        public int IdNotasDebito { get; set; }
        public Nullable<int> IdEmpleadoSolicita { get; set; }
        public Nullable<int> IdEmpleadoAprueba { get; set; }
        public Nullable<int> IdBeneficiario { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Consecutivo { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public string TipoBeneficiario { get; set; }
        public string Moneda { get; set; }
        public string Observacion { get; set; }
        public string Estado { get; set; }
        public string SerieConsecutivo { get; set; }
        public Nullable<decimal> Tasa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleNotasDebito> DetalleNotasDebito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleNotaDebitoRetencion> DetalleNotaDebitoRetencion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleReciboCajaGeneralNota> DetalleReciboCajaGeneralNota { get; set; }
    }
}
