//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificacionUsuario
    {
        public int IdNotificacionUsuario { get; set; }
        public Nullable<int> IdNotificacion { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdRemitente { get; set; }
    
        public virtual Notificacion Notificacion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
