//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenTrabajo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenTrabajo()
        {
            this.AccesorioOrdenTrabajo = new HashSet<AccesorioOrdenTrabajo>();
            this.AsignacionTecnicoServicio = new HashSet<AsignacionTecnicoServicio>();
            this.AsignarProductos = new HashSet<AsignarProductos>();
            this.CotizacionOT = new HashSet<CotizacionOT>();
            this.EstadosOT = new HashSet<EstadosOT>();
            this.ImagenesVehiculoOT = new HashSet<ImagenesVehiculoOT>();
            this.MantenimientoOrdenTrabajo = new HashSet<MantenimientoOrdenTrabajo>();
            this.PreFacturaInternaOT = new HashSet<PreFacturaInternaOT>();
            this.PreFacturaOT = new HashSet<PreFacturaOT>();
            this.TrabajosExternos = new HashSet<TrabajosExternos>();
            this.VehiculoEnProceso = new HashSet<VehiculoEnProceso>();
            this.PruebaVehiculo = new HashSet<PruebaVehiculo>();
            this.SolicitudAperturaOT = new HashSet<SolicitudAperturaOT>();
        }
    
        public int IdOrdenTrabajo { get; set; }
        public Nullable<int> IdFlotaVehicular { get; set; }
        public Nullable<int> IdPropietario { get; set; }
        public string TipoCliente { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public string Consecutivo { get; set; }
        public string NoReclamo { get; set; }
        public string PersonaEntrega { get; set; }
        public Nullable<int> NivelCombustible { get; set; }
        public Nullable<double> Kilometraje { get; set; }
        public string Suciedad { get; set; }
        public Nullable<decimal> Duracion { get; set; }
        public byte[] ReporteDaños { get; set; }
        public string Lavado { get; set; }
        public string Observacion { get; set; }
        public string Sintomas { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public string SerieConsecutivo { get; set; }
        public string TipoReclamo { get; set; }
    
        public virtual FlotaVehicular FlotaVehicular { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccesorioOrdenTrabajo> AccesorioOrdenTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionTecnicoServicio> AsignacionTecnicoServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignarProductos> AsignarProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CotizacionOT> CotizacionOT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstadosOT> EstadosOT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagenesVehiculoOT> ImagenesVehiculoOT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MantenimientoOrdenTrabajo> MantenimientoOrdenTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreFacturaInternaOT> PreFacturaInternaOT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreFacturaOT> PreFacturaOT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrabajosExternos> TrabajosExternos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehiculoEnProceso> VehiculoEnProceso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PruebaVehiculo> PruebaVehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudAperturaOT> SolicitudAperturaOT { get; set; }
    }
}
