//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenProduccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenProduccion()
        {
            this.AsignarTecnicosOrdenProduccion = new HashSet<AsignarTecnicosOrdenProduccion>();
            this.IngresoOrdenProduccion = new HashSet<IngresoOrdenProduccion>();
            this.ProcesarOrdenProduccion = new HashSet<ProcesarOrdenProduccion>();
            this.ProductoMaloOP = new HashSet<ProductoMaloOP>();
            this.ProductosDefectuosos = new HashSet<ProductosDefectuosos>();
            this.SolicitudCostosProduccion = new HashSet<SolicitudCostosProduccion>();
        }
    
        public int IdOrdenProduccion { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public string Consecutivo { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public string Observacion { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public string SerieConsecutivo { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignarTecnicosOrdenProduccion> AsignarTecnicosOrdenProduccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngresoOrdenProduccion> IngresoOrdenProduccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcesarOrdenProduccion> ProcesarOrdenProduccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoMaloOP> ProductoMaloOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductosDefectuosos> ProductosDefectuosos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudCostosProduccion> SolicitudCostosProduccion { get; set; }
    }
}
