//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagoRealizadoTesoreria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PagoRealizadoTesoreria()
        {
            this.DetallePagoRealizadoTesoreria = new HashSet<DetallePagoRealizadoTesoreria>();
            this.MovimientoBancario = new HashSet<MovimientoBancario>();
        }
    
        public int IdPagoRealizadoTesoreria { get; set; }
        public Nullable<int> IdEncargado { get; set; }
        public Nullable<int> IdCuentaBanco { get; set; }
        public Nullable<int> IdCuentaBeneficiario { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public string Consecutivo { get; set; }
        public string TipoPago { get; set; }
        public Nullable<decimal> MontoTotalPago { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<int> IdCuentaContable { get; set; }
        public string SerieConsecutivo { get; set; }
    
        public virtual CatalogoCuenta CatalogoCuenta { get; set; }
        public virtual CuentaBanco CuentaBanco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePagoRealizadoTesoreria> DetallePagoRealizadoTesoreria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovimientoBancario> MovimientoBancario { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
