//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecioCombo
    {
        public int IdPrecioCombo { get; set; }
        public Nullable<int> IdSegmento { get; set; }
        public Nullable<decimal> Factor { get; set; }
        public Nullable<decimal> FactorMinimo { get; set; }
        public Nullable<int> IdCombo { get; set; }
    
        public virtual ComboProducto ComboProducto { get; set; }
        public virtual Segmento Segmento { get; set; }
    }
}
