//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrecioProducto
    {
        public int IdPrecioProducto { get; set; }
        public Nullable<int> IdSegmento { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<decimal> Factor { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<decimal> FactorMinimo { get; set; }
        public Nullable<decimal> PrecioBase { get; set; }
        public Nullable<decimal> PrecioMinimo { get; set; }
        public Nullable<System.DateTime> FechaTasa { get; set; }
        public string Moneda { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Segmento Segmento { get; set; }
    }
}
