//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrefacturaVenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrefacturaVenta()
        {
            this.DetallePrefacturaV = new HashSet<DetallePrefacturaV>();
        }
    
        public int IdPrefactura { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdVendedor { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdBodega { get; set; }
        public Nullable<int> IdSegmento { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public Nullable<int> IdCotizacion { get; set; }
        public string Consecutivo { get; set; }
        public string SerieConsecutivo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string TipoPago { get; set; }
        public Nullable<decimal> TasaCambio { get; set; }
        public string TipoMoneda { get; set; }
        public Nullable<int> PlazoDias { get; set; }
        public string Estado { get; set; }
    
        public virtual Bodega Bodega { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual CotizacionVenta CotizacionVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePrefacturaV> DetallePrefacturaV { get; set; }
        public virtual Vendedor Vendedor { get; set; }
    }
}
