//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreFacturaInternaOT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PreFacturaInternaOT()
        {
            this.AprobarPrefacturaInternaOT = new HashSet<AprobarPrefacturaInternaOT>();
            this.DetallePreFacturaInternaOT = new HashSet<DetallePreFacturaInternaOT>();
            this.EmpleadosPreFacturaInternaOT = new HashSet<EmpleadosPreFacturaInternaOT>();
        }
    
        public int IdPreFacturaInternaOT { get; set; }
        public Nullable<int> IdOrdenTrabajo { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public string Consecutivo { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> TasaParalelo { get; set; }
        public string TipoPago { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> IdVendedor { get; set; }
        public string TipoMoneda { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AprobarPrefacturaInternaOT> AprobarPrefacturaInternaOT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePreFacturaInternaOT> DetallePreFacturaInternaOT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpleadosPreFacturaInternaOT> EmpleadosPreFacturaInternaOT { get; set; }
        public virtual OrdenTrabajo OrdenTrabajo { get; set; }
    }
}
