//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrefacturaExcenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrefacturaExcenta()
        {
            this.DetalleExcento = new HashSet<DetalleExcento>();
        }
    
        public int IdExcentoIVA { get; set; }
        public string CodigoAutorizado { get; set; }
        public Nullable<System.DateTime> FechaRealizado { get; set; }
        public Nullable<int> IdEncargado { get; set; }
        public string Consecutivo { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public string SerieConsecutivo { get; set; }
        public Nullable<int> IdDocumento { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleExcento> DetalleExcento { get; set; }
    }
}
