//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Celular = new HashSet<Celular>();
            this.DetalleComboProducto = new HashSet<DetalleComboProducto>();
            this.DetalleCombosProducto = new HashSet<DetalleCombosProducto>();
            this.DetalleCompra = new HashSet<DetalleCompra>();
            this.DetalleCotizacionV = new HashSet<DetalleCotizacionV>();
            this.DetalleDevolucionCompra = new HashSet<DetalleDevolucionCompra>();
            this.DetallePrefacturaV = new HashSet<DetallePrefacturaV>();
            this.DetalleProductoMaloOP = new HashSet<DetalleProductoMaloOP>();
            this.DetalleReversionDocumento = new HashSet<DetalleReversionDocumento>();
            this.DetalleSalidaInventario = new HashSet<DetalleSalidaInventario>();
            this.DetalleTraslado = new HashSet<DetalleTraslado>();
            this.DetalleTrasladoAprobado = new HashSet<DetalleTrasladoAprobado>();
            this.DetalleTrasladoSolicitado = new HashSet<DetalleTrasladoSolicitado>();
            this.Imagen = new HashSet<Imagen>();
            this.Kardex = new HashSet<Kardex>();
            this.Margen = new HashSet<Margen>();
            this.PrecioProducto = new HashSet<PrecioProducto>();
            this.DetalleAsignarProductos = new HashSet<DetalleAsignarProductos>();
            this.DetallePeticionCompra = new HashSet<DetallePeticionCompra>();
            this.DetalleProductosCotizacionOT = new HashSet<DetalleProductosCotizacionOT>();
            this.DetallePreFacturaInternaOT = new HashSet<DetallePreFacturaInternaOT>();
            this.DetallePreFacturaOT = new HashSet<DetallePreFacturaOT>();
            this.Vehiculo = new HashSet<Vehiculo>();
        }
    
        public int IdProducto { get; set; }
        public Nullable<int> IdUnidadMedida { get; set; }
        public Nullable<int> IdUnidadPeso { get; set; }
        public Nullable<int> IdMarca { get; set; }
        public Nullable<int> IdRubro { get; set; }
        public Nullable<int> IdLinea { get; set; }
        public int IdEmpresa { get; set; }
        public string CodigoAlterno { get; set; }
        public string CodigoOriginal { get; set; }
        public string Descripcion { get; set; }
        public string Dimensiones { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public string Nombre { get; set; }
        public Nullable<bool> ManejaIdentificador { get; set; }
        public Nullable<bool> ManejaLote { get; set; }
        public string TipoCosteo { get; set; }
        public Nullable<bool> TieneIVA { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Celular> Celular { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleComboProducto> DetalleComboProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCombosProducto> DetalleCombosProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCompra> DetalleCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCotizacionV> DetalleCotizacionV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleDevolucionCompra> DetalleDevolucionCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePrefacturaV> DetallePrefacturaV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleProductoMaloOP> DetalleProductoMaloOP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleReversionDocumento> DetalleReversionDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleSalidaInventario> DetalleSalidaInventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleTraslado> DetalleTraslado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleTrasladoAprobado> DetalleTrasladoAprobado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleTrasladoSolicitado> DetalleTrasladoSolicitado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imagen> Imagen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kardex> Kardex { get; set; }
        public virtual Linea Linea { get; set; }
        public virtual Marca Marca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Margen> Margen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrecioProducto> PrecioProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleAsignarProductos> DetalleAsignarProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePeticionCompra> DetallePeticionCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleProductosCotizacionOT> DetalleProductosCotizacionOT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePreFacturaInternaOT> DetallePreFacturaInternaOT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePreFacturaOT> DetallePreFacturaOT { get; set; }
        public virtual Rubro Rubro { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
        public virtual UnidadPeso UnidadPeso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehiculo> Vehiculo { get; set; }
    }
}
