//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramarPago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProgramarPago()
        {
            this.ConfirmarPago = new HashSet<ConfirmarPago>();
        }
    
        public int IdProgramarPago { get; set; }
        public int IdFactura { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<decimal> MontoPorcentaje { get; set; }
        public Nullable<decimal> TotalApagar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfirmarPago> ConfirmarPago { get; set; }
    }
}
