//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedor()
        {
            this.Criterio_Proveedor = new HashSet<Criterio_Proveedor>();
            this.ConfirmarMantenimiento = new HashSet<ConfirmarMantenimiento>();
            this.CotizarMantenimiento = new HashSet<CotizarMantenimiento>();
            this.FacturaCombustible = new HashSet<FacturaCombustible>();
            this.AcompañamientoProveedor = new HashSet<AcompañamientoProveedor>();
            this.Compra = new HashSet<Compra>();
            this.DetalleServiciosImportacion = new HashSet<DetalleServiciosImportacion>();
            this.Linea = new HashSet<Linea>();
            this.CotizacionCompra = new HashSet<CotizacionCompra>();
            this.TrabajosExternos = new HashSet<TrabajosExternos>();
            this.ProveedorContacto = new HashSet<ProveedorContacto>();
            this.ProveedorBancario = new HashSet<ProveedorBancario>();
        }
    
        public int IdProveedor { get; set; }
        public string RucProveedor { get; set; }
        public string NombreProveedor { get; set; }
        public string CondicionPago { get; set; }
        public Nullable<int> Plazo { get; set; }
        public decimal Monto { get; set; }
        public string Pais { get; set; }
        public string Ciudad { get; set; }
        public string Web { get; set; }
        public string RedSocial { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string Codigo { get; set; }
        public string Nacionalidad { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string GiroProveedor { get; set; }
        public Nullable<decimal> Anticipo { get; set; }
        public string CondicionPlazo { get; set; }
        public string PuertoEmbarque { get; set; }
        public string PuertoDesembarque { get; set; }
        public string RazonSocial { get; set; }
        public string Direccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Criterio_Proveedor> Criterio_Proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfirmarMantenimiento> ConfirmarMantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CotizarMantenimiento> CotizarMantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaCombustible> FacturaCombustible { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcompañamientoProveedor> AcompañamientoProveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleServiciosImportacion> DetalleServiciosImportacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Linea> Linea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CotizacionCompra> CotizacionCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrabajosExternos> TrabajosExternos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProveedorContacto> ProveedorContacto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProveedorBancario> ProveedorBancario { get; set; }
    }
}
