//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PruebaVehiculo
    {
        public int IdPruebaVehiculo { get; set; }
        public string Consecutivo { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public string SerieConsecutivo { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public Nullable<System.DateTime> FechaRetorno { get; set; }
        public string ObservacionSalida { get; set; }
        public string ObservacionRetorno { get; set; }
        public Nullable<int> IdAgenteProbador { get; set; }
        public Nullable<int> IdAprobacionSalida { get; set; }
        public Nullable<int> IdAprobacionRetorno { get; set; }
        public Nullable<decimal> KilometrajeSalida { get; set; }
        public Nullable<decimal> KilomentrajeEntrada { get; set; }
        public Nullable<int> IdOrdenTrabajo { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual OrdenTrabajo OrdenTrabajo { get; set; }
    }
}
