//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Puesto()
        {
            this.AlcancePuesto = new HashSet<AlcancePuesto>();
            this.DocumentoPuesto = new HashSet<DocumentoPuesto>();
            this.EmpleadoPuesto = new HashSet<EmpleadoPuesto>();
            this.EnfermedadPuesto = new HashSet<EnfermedadPuesto>();
            this.HerramientaPuesto = new HashSet<HerramientaPuesto>();
            this.IndicadorDesempeñoPuesto = new HashSet<IndicadorDesempeñoPuesto>();
            this.InfoPuesto = new HashSet<InfoPuesto>();
            this.RiesgoPuesto = new HashSet<RiesgoPuesto>();
            this.RequisitoPuesto = new HashSet<RequisitoPuesto>();
            this.TareaPuesto = new HashSet<TareaPuesto>();
        }
    
        public int IdPuesto { get; set; }
        public string Puesto1 { get; set; }
        public string Resumen { get; set; }
        public string Relaciones { get; set; }
        public string NivelAcademico { get; set; }
        public string ExperienciaPrevia { get; set; }
        public string Lugar { get; set; }
        public string Objetivos { get; set; }
        public decimal SalarioMinimo { get; set; }
        public decimal SalarioMaximo { get; set; }
        public string TipoMoneda { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> IdPuestoSuperior { get; set; }
        public Nullable<int> PlazasTotales { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlcancePuesto> AlcancePuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentoPuesto> DocumentoPuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpleadoPuesto> EmpleadoPuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnfermedadPuesto> EnfermedadPuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HerramientaPuesto> HerramientaPuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndicadorDesempeñoPuesto> IndicadorDesempeñoPuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoPuesto> InfoPuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiesgoPuesto> RiesgoPuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitoPuesto> RequisitoPuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TareaPuesto> TareaPuesto { get; set; }
    }
}
