//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReciboCajaChica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReciboCajaChica()
        {
            this.DetalleReciboCajaChica = new HashSet<DetalleReciboCajaChica>();
            this.SolicitudReciboReembolso = new HashSet<SolicitudReciboReembolso>();
        }
    
        public int IdReciboCajaChica { get; set; }
        public Nullable<int> IdAsignacionCajaChica { get; set; }
        public Nullable<int> IdEmpleadoElaboraRecibo { get; set; }
        public Nullable<int> IdUnidad { get; set; }
        public string TipoPersona { get; set; }
        public Nullable<int> IdBeneficiario { get; set; }
        public string NombreBeneficiario { get; set; }
        public string ObservacionGasto { get; set; }
        public Nullable<System.DateTime> FechaElaboracion { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public string Consecutivo { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string CedulaRuc { get; set; }
        public Nullable<int> IdSolicitudPagoCajaChica { get; set; }
        public string NumeroLetra { get; set; }
    
        public virtual AsignacionCajaChica AsignacionCajaChica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleReciboCajaChica> DetalleReciboCajaChica { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual SolicitudPagoCajaChica SolicitudPagoCajaChica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudReciboReembolso> SolicitudReciboReembolso { get; set; }
    }
}
