//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReciboCajaGeneral
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReciboCajaGeneral()
        {
            this.AnulacionReciboGeneral = new HashSet<AnulacionReciboGeneral>();
            this.DetalleReciboCajaGeneral = new HashSet<DetalleReciboCajaGeneral>();
            this.DetalleReciboCajaGeneralNota = new HashSet<DetalleReciboCajaGeneralNota>();
            this.Retenciones = new HashSet<Retenciones>();
        }
    
        public int IdReciboCajaGeneral { get; set; }
        public Nullable<int> IdEmpleadoRElaboraRecibo { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public string Consecutivo { get; set; }
        public Nullable<System.DateTime> FechaHoraElaboracion { get; set; }
        public Nullable<System.DateTime> FechaHoraPago { get; set; }
        public string ObservacionPago { get; set; }
        public string Estado { get; set; }
        public string TipoMoneda { get; set; }
        public string ValorLetras { get; set; }
        public string TipoPago { get; set; }
        public Nullable<int> IdDescripcionConceptoCaja { get; set; }
        public Nullable<decimal> MontoAbonado { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<bool> AplicaFacturas { get; set; }
        public Nullable<int> IdAperturaCaja { get; set; }
        public Nullable<int> IdCaja { get; set; }
        public string TipoPersona { get; set; }
        public Nullable<bool> CancelarFacturas { get; set; }
        public string NoDocumentoRetencion { get; set; }
        public string MonedaRetencion { get; set; }
        public Nullable<System.DateTime> FechaRetencion { get; set; }
        public Nullable<decimal> MontoRetencion { get; set; }
    
        public virtual DescripcionConceptoCaja DescripcionConceptoCaja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnulacionReciboGeneral> AnulacionReciboGeneral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleReciboCajaGeneral> DetalleReciboCajaGeneral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleReciboCajaGeneralNota> DetalleReciboCajaGeneralNota { get; set; }
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Retenciones> Retenciones { get; set; }
    }
}
