//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int IdReserva { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaValidez { get; set; }
        public string Observacion { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdBodega { get; set; }
        public Nullable<int> IdCotizacion { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
    
        public virtual Bodega Bodega { get; set; }
        public virtual CotizacionVenta CotizacionVenta { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
