//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Retenciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Retenciones()
        {
            this.RetencionesDetalle = new HashSet<RetencionesDetalle>();
        }
    
        public int IdRetenciones { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public string Consecutivo { get; set; }
        public Nullable<System.DateTime> FechaRealizacion { get; set; }
        public Nullable<System.DateTime> FechaRetencion { get; set; }
        public Nullable<int> IdEmpledoSolicita { get; set; }
        public Nullable<int> IdReciboCajaGeneral { get; set; }
        public Nullable<decimal> TasaOficial { get; set; }
        public Nullable<int> IdEmpleadoProcesa { get; set; }
        public Nullable<System.DateTime> FechaProcesada { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> Status { get; set; }
        public string TipoPersona { get; set; }
        public string SerieConsecutivo { get; set; }
    
        public virtual ReciboCajaGeneral ReciboCajaGeneral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RetencionesDetalle> RetencionesDetalle { get; set; }
    }
}
