//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetencionesProveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RetencionesProveedor()
        {
            this.DetalleRetencionesProveedor = new HashSet<DetalleRetencionesProveedor>();
        }
    
        public int IdRetencionesProveedor { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public string Consecutivo { get; set; }
        public Nullable<System.DateTime> FechaRetencion { get; set; }
        public Nullable<int> IdEmpleadoSolicita { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public string Moneda { get; set; }
        public Nullable<decimal> TasaOficial { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> IdEmpleadoAprueba { get; set; }
        public Nullable<System.DateTime> FechaAprueba { get; set; }
        public string Estado { get; set; }
        public string SerieConsecutivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleRetencionesProveedor> DetalleRetencionesProveedor { get; set; }
    }
}
