//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReversionDocumento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReversionDocumento()
        {
            this.DetalleReversionDocumento = new HashSet<DetalleReversionDocumento>();
            this.IdentificadoresReversion = new HashSet<IdentificadoresReversion>();
        }
    
        public int IdReversion { get; set; }
        public Nullable<int> IdDocumento { get; set; }
        public string Documento { get; set; }
        public Nullable<int> IdBodega { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Consecutivo { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public string SerieConsecutivo { get; set; }
        public string Tipo { get; set; }
    
        public virtual Bodega Bodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleReversionDocumento> DetalleReversionDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdentificadoresReversion> IdentificadoresReversion { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
