//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevisarCotizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RevisarCotizacion()
        {
            this.DetalleRevisarCotizacion = new HashSet<DetalleRevisarCotizacion>();
        }
    
        public int IdRevisarCotizacion { get; set; }
        public Nullable<int> IdEncargadoAprobacion { get; set; }
        public Nullable<int> IdEncargadoRevision { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public Nullable<System.DateTime> FechaRevision { get; set; }
        public string Procedencia { get; set; }
        public Nullable<int> Identificador { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdRevisador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleRevisarCotizacion> DetalleRevisarCotizacion { get; set; }
    }
}
