//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalidaInventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalidaInventario()
        {
            this.DetalleSalidaInventario = new HashSet<DetalleSalidaInventario>();
        }
    
        public int IdSalidaInventario { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public string Consecutivo { get; set; }
        public Nullable<int> IdEmpleadoSolicita { get; set; }
        public Nullable<int> IdEmpleadoAprueba { get; set; }
        public Nullable<int> IdBodega { get; set; }
        public Nullable<int> IdConcepto { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string SerieConsecutivo { get; set; }
    
        public virtual ConceptoSalidaInventario ConceptoSalidaInventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleSalidaInventario> DetalleSalidaInventario { get; set; }
    }
}
