//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Serie()
        {
            this.DescuentoxProntoPago = new HashSet<DescuentoxProntoPago>();
            this.Traslado = new HashSet<Traslado>();
        }
    
        public int IdSerie { get; set; }
        public string NombreSerie { get; set; }
        public Nullable<long> Consecutivo { get; set; }
        public Nullable<int> Digitos { get; set; }
        public string Prefijo { get; set; }
        public string CodigoVerificacion { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public Nullable<int> IdDocumento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DescuentoxProntoPago> DescuentoxProntoPago { get; set; }
        public virtual DocumentoSerie DocumentoSerie { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Traslado> Traslado { get; set; }
    }
}
