//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiciosImportacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiciosImportacion()
        {
            this.DetalleServiciosImportacion = new HashSet<DetalleServiciosImportacion>();
            this.DetallesImpuestos = new HashSet<DetallesImpuestos>();
        }
    
        public int IdServiciosImportacion { get; set; }
        public Nullable<int> NoUnico { get; set; }
        public string NoFactura { get; set; }
        public string NoPoliza { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleServiciosImportacion> DetalleServiciosImportacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesImpuestos> DetallesImpuestos { get; set; }
    }
}
