//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudReciboReembolso
    {
        public int IdSolicitudReciboReembolso { get; set; }
        public Nullable<int> IdSolicitudReembolsoCajaChica { get; set; }
        public Nullable<int> IdReciboCajaChica { get; set; }
    
        public virtual ReciboCajaChica ReciboCajaChica { get; set; }
        public virtual SolicitudReembolsoCajaChica SolicitudReembolsoCajaChica { get; set; }
    }
}
