//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudAperturaOT
    {
        public int IdSolicitudAperturaOT { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<int> IdSolicitante { get; set; }
        public string ObservacionSolicitud { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public Nullable<int> IdEncargadoAprobacion { get; set; }
        public string ObservacionAprobacion { get; set; }
        public string EstadoSolicitud { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public Nullable<int> IdOrdenTrabajo { get; set; }
        public string TipoSolicitud { get; set; }
    
        public virtual OrdenTrabajo OrdenTrabajo { get; set; }
    }
}
