//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudPermisoSistema
    {
        public int IdSolicitudPermisoSistema { get; set; }
        public Nullable<int> IdEmpleadoSolicita { get; set; }
        public Nullable<int> IdTipoCuenta { get; set; }
        public string Modulo { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public Nullable<System.DateTime> FechaOtorgacion { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> Ver { get; set; }
        public Nullable<bool> Guardar { get; set; }
        public Nullable<bool> Modificar { get; set; }
        public Nullable<bool> Anular { get; set; }
        public Nullable<int> IdEmpleadoAprueba { get; set; }
        public string TipoSolicitud { get; set; }
        public Nullable<int> IdEmpleadoOtorga { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
