//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudTraslado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SolicitudTraslado()
        {
            this.DetalleTrasladoSolicitado = new HashSet<DetalleTrasladoSolicitado>();
            this.Traslado = new HashSet<Traslado>();
        }
    
        public int IdSolicitudTraslado { get; set; }
        public Nullable<int> SolicitadoPor { get; set; }
        public Nullable<int> AprobadoPor { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<int> BodegaDestino { get; set; }
        public Nullable<int> BodegaOrigen { get; set; }
        public string Estado { get; set; }
        public string Descripcion { get; set; }
        public string TipoSolicitud { get; set; }
        public string NivelRelevancia { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public string Consecutivo { get; set; }
        public Nullable<int> IdVerificacionTransf { get; set; }
        public Nullable<System.DateTime> FechaAprobado { get; set; }
    
        public virtual Bodega Bodega { get; set; }
        public virtual Bodega Bodega1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleTrasladoSolicitado> DetalleTrasladoSolicitado { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Empleado Empleado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Traslado> Traslado { get; set; }
    }
}
