//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitarProductosOP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SolicitarProductosOP()
        {
            this.SolicitarProductosOPDetalle = new HashSet<SolicitarProductosOPDetalle>();
        }
    
        public int IdSolicitarProductosOP { get; set; }
        public Nullable<int> IdAsignarTecnicosOrdenProduccion { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaProcesada { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual AsignarTecnicosOrdenProduccion AsignarTecnicosOrdenProduccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitarProductosOPDetalle> SolicitarProductosOPDetalle { get; set; }
    }
}
