//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudCheque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SolicitudCheque()
        {
            this.DetallePagoRealizadoTesoreria = new HashSet<DetallePagoRealizadoTesoreria>();
            this.DetalleSolicitudCheque = new HashSet<DetalleSolicitudCheque>();
        }
    
        public int IdSolicitudCheque { get; set; }
        public Nullable<int> IdEmpleadoSolicita { get; set; }
        public Nullable<int> IdBeneficiario { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public Nullable<int> IdDepartamentoDirigido { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string TipoBeneficiario { get; set; }
        public string Consecutivo { get; set; }
        public string EnConceptoDe { get; set; }
        public string TipoMoneda { get; set; }
        public Nullable<decimal> MontoCheque { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaAprobacionDenegacion { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> SRendicion { get; set; }
        public string SerieConsecutivo { get; set; }
        public Nullable<int> IdEmpleadoAprueba { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePagoRealizadoTesoreria> DetallePagoRealizadoTesoreria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleSolicitudCheque> DetalleSolicitudCheque { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
