//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudPaseCredito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SolicitudPaseCredito()
        {
            this.AprobarSolicitudPaseCredito = new HashSet<AprobarSolicitudPaseCredito>();
        }
    
        public int IdSolicitudPaseCredito { get; set; }
        public string Consecutivo { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdSeguimientoCliente { get; set; }
        public Nullable<int> IdPrefacturaPV { get; set; }
        public Nullable<int> IdPrefacturaOT { get; set; }
        public Nullable<decimal> CreditoSolicitado { get; set; }
        public string Moneda { get; set; }
        public Nullable<decimal> TasaCambio { get; set; }
        public string Concepto { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public string SerieConsecutivo { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public string Estado { get; set; }
        public string ObservacionProcesar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AprobarSolicitudPaseCredito> AprobarSolicitudPaseCredito { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual ClienteSeguimiento ClienteSeguimiento { get; set; }
    }
}
