//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudCredito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SolicitudCredito()
        {
            this.ProcesamientoCreditoCliente = new HashSet<ProcesamientoCreditoCliente>();
        }
    
        public int IdSolicitudCredito { get; set; }
        public Nullable<int> IdClienteSeguimiento { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public string CondicionPago { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> Plazo { get; set; }
        public string Observacion { get; set; }
        public string Estado { get; set; }
        public string TipoSolicitud { get; set; }
        public Nullable<System.DateTime> FechaProcesado { get; set; }
        public Nullable<System.DateTime> FechaRecibido { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
    
        public virtual ClienteSeguimiento ClienteSeguimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcesamientoCreditoCliente> ProcesamientoCreditoCliente { get; set; }
    }
}
