//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tecnico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tecnico()
        {
            this.DetalleAsignarTecnicosOrdenProduccion = new HashSet<DetalleAsignarTecnicosOrdenProduccion>();
        }
    
        public int IdTecnico { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<int> IdUbicacion { get; set; }
        public string Categoria { get; set; }
        public string Puesto { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleAsignarTecnicosOrdenProduccion> DetalleAsignarTecnicosOrdenProduccion { get; set; }
        public virtual UbicacionFabrica UbicacionFabrica { get; set; }
    }
}
