//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TitulosReportes
    {
        public int IdTitulo { get; set; }
        public string NombreTitulo { get; set; }
        public string LeyendaReporte { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public string CodigoFacturacion { get; set; }
    }
}
