//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrasladoOrdenProduccion
    {
        public int IdTrasladoOrdenTrabajo { get; set; }
        public Nullable<int> IdTraslado { get; set; }
        public Nullable<int> IdOrdenProduccion { get; set; }
        public Nullable<int> IdAsignarProductos { get; set; }
    
        public virtual Traslado Traslado { get; set; }
    }
}
