//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traslado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Traslado()
        {
            this.AnulacionTraslado = new HashSet<AnulacionTraslado>();
            this.DespachoTraslado = new HashSet<DespachoTraslado>();
            this.DetalleTraslado = new HashSet<DetalleTraslado>();
            this.TrasladoOrdenProduccion = new HashSet<TrasladoOrdenProduccion>();
            this.TrasladoOrdenTrabajo = new HashSet<TrasladoOrdenTrabajo>();
        }
    
        public int IdTraslado { get; set; }
        public Nullable<int> IdSolitudTraslado { get; set; }
        public string ObservacionEntrega { get; set; }
        public string Consecutivo { get; set; }
        public Nullable<int> IdSerie { get; set; }
        public Nullable<int> GeneradoPor { get; set; }
        public Nullable<int> BodegaOrigen { get; set; }
        public Nullable<int> BodegaDestino { get; set; }
        public Nullable<System.DateTime> FechaAprobado { get; set; }
        public string TipoTraslado { get; set; }
        public string Estado { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnulacionTraslado> AnulacionTraslado { get; set; }
        public virtual Bodega Bodega { get; set; }
        public virtual Bodega Bodega1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DespachoTraslado> DespachoTraslado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleTraslado> DetalleTraslado { get; set; }
        public virtual Serie Serie { get; set; }
        public virtual SolicitudTraslado SolicitudTraslado { get; set; }
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrasladoOrdenProduccion> TrasladoOrdenProduccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrasladoOrdenTrabajo> TrasladoOrdenTrabajo { get; set; }
    }
}
