//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.BitacoraUsuarioModulo = new HashSet<BitacoraUsuarioModulo>();
            this.NotificacionUsuario = new HashSet<NotificacionUsuario>();
        }
    
        public int IdUsuario { get; set; }
        public string Usuario1 { get; set; }
        public string Contaseña { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<int> IdTipoCuenta { get; set; }
        public int IdEmpleado { get; set; }
        public string Tema { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BitacoraUsuarioModulo> BitacoraUsuarioModulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificacionUsuario> NotificacionUsuario { get; set; }
        public virtual TipoCuenta TipoCuenta { get; set; }
    }
}
