//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public int IdVehiculo { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public string Modelo { get; set; }
        public string TipoVehiculo { get; set; }
        public string Motor { get; set; }
        public int Anio { get; set; }
        public string Combustible { get; set; }
        public string Cilindraje { get; set; }
        public Nullable<int> Pasajeros { get; set; }
        public Nullable<decimal> Tonelaje { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
