//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiculoProcesoEstaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehiculoProcesoEstaciones()
        {
            this.MecanicosVehiculoProceso = new HashSet<MecanicosVehiculoProceso>();
        }
    
        public int IdVehiculoProcesoEstaciones { get; set; }
        public Nullable<int> IdVehiculoProceso { get; set; }
        public Nullable<int> IdEstacionTrabajo { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual EstacionTrabajo EstacionTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MecanicosVehiculoProceso> MecanicosVehiculoProceso { get; set; }
        public virtual VehiculoEnProceso VehiculoEnProceso { get; set; }
    }
}
