//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehiculoEnProceso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VehiculoEnProceso()
        {
            this.VehiculoProcesoEstaciones = new HashSet<VehiculoProcesoEstaciones>();
        }
    
        public int IdVehiculoEnProceso { get; set; }
        public Nullable<int> IdOrdenTrabajo { get; set; }
        public Nullable<System.DateTime> Ingreso { get; set; }
        public Nullable<System.DateTime> Salida { get; set; }
        public string Descripcion { get; set; }
        public string Estado { get; set; }
    
        public virtual OrdenTrabajo OrdenTrabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehiculoProcesoEstaciones> VehiculoProcesoEstaciones { get; set; }
    }
}
