//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendedor()
        {
            this.CarteraCliente = new HashSet<CarteraCliente>();
            this.Consignacion = new HashSet<Consignacion>();
            this.CotizacionVenta = new HashSet<CotizacionVenta>();
            this.PrefacturaVenta = new HashSet<PrefacturaVenta>();
        }
    
        public int IdVendedor { get; set; }
        public string CodigoVendedor { get; set; }
        public Nullable<decimal> MontoConsignacion { get; set; }
        public Nullable<int> IdSegmento { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<bool> AlterarPrecio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarteraCliente> CarteraCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consignacion> Consignacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CotizacionVenta> CotizacionVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrefacturaVenta> PrefacturaVenta { get; set; }
        public virtual Segmento Segmento { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
