//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerificacionTransferencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VerificacionTransferencia()
        {
            this.DetalleVerificacionSolicitudes = new HashSet<DetalleVerificacionSolicitudes>();
        }
    
        public int IdVerificacionTransfer { get; set; }
        public Nullable<int> IdBuscador { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdSolicitudTraslado { get; set; }
        public Nullable<int> IdTraslado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVerificacionSolicitudes> DetalleVerificacionSolicitudes { get; set; }
    }
}
