//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwDetallesCompra
    {
        public int IdCompra { get; set; }
        public int IdDetalleCompra { get; set; }
        public string CodigoAlterno { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
