//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CotizadorWeb.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwSeries
    {
        public int IdSerie { get; set; }
        public string NombreSerie { get; set; }
        public Nullable<long> Consecutivo { get; set; }
        public Nullable<int> Digitos { get; set; }
        public string Prefijo { get; set; }
        public string CodigoVerificacion { get; set; }
        public Nullable<int> IdSucursal { get; set; }
        public Nullable<int> IdDocumento { get; set; }
        public string Serie { get; set; }
        public string NombreSucursal { get; set; }
        public string NombreDocumento { get; set; }
    }
}
